# Generated by Django 2.0.4 on 2018-04-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='product_cart',
        ),
    ]
